import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { SelectModule } from 'primeng/select';
import { CommonModule } from '@angular/common';
import {EventEmitter, Input, Output } from '@angular/core';
import { DropdownModule } from 'primeng/dropdown';

@Component({
  selector: 'app-menu-paesi',
  imports: [CommonModule, FormsModule, DropdownModule],
  templateUrl: './menu-paesi.component.html',
  styleUrl: './menu-paesi.component.css'
})
export class MenuPaesiComponent implements OnInit {
  @Input() selectedCurrency!: { code: string };
  @Output() selectedCurrencyChange = new EventEmitter<{ code: string }>();

  currencies: { code: string }[] = [];
  currencyCodes: { code: string }[] = [];

ngOnInit() {
  //lista paesi
  this.currencies = [
    { code: 'USD' }, { code: 'EUR' }, { code: 'GBP' }, { code: 'INR' },

  ];

  this.currencyCodes = [
    { code: 'Afghanistan (AFN)' },
    { code: 'Albania (ALL)' },
    { code: 'Algeria (DZD)' },
    { code: 'Andorra (EUR)' },
    { code: 'Angola (AOA)' },
    { code: 'Antigua e Barbuda (XCD)' },
    { code: 'Argentina (ARS)' },
    { code: 'Armenia (AMD)' },
    { code: 'Australia (AUD)' },
    { code: 'Austria (EUR)' },
    { code: 'Azerbaigian (AZN)' },
    { code: 'Bahamas (BSD)' },
    { code: 'Bahrein (BHD)' },
    { code: 'Bangladesh (BDT)' },
    { code: 'Barbados (BBD)' },
    { code: 'Belgio (EUR)' },
    { code: 'Belize (BZD)' },
    { code: 'Benin (XOF)' },
    { code: 'Bhutan (BTN)' },
    { code: 'Bolivia (BOB)' },
    { code: 'Bosnia ed Erzegovina (BAM)' },
    { code: 'Botswana (BWP)' },
    { code: 'Brasile (BRL)' },
    { code: 'Brunei (BND)' },
    { code: 'Bulgaria (BGN)' },
    { code: 'Burkina Faso (BFA)' },
    { code: 'Burundi (BIF)' },
    { code: 'Cabo Verde (CVE)' },
    { code: 'Cambogia (KHR)' },
    { code: 'Camerun (CDF)' },
    { code: 'Canada (CAD)' },
    { code: 'Ciad (CFA)' },
    { code: 'Cile (CLP)' },
    { code: 'Cina (CNY)' },
    { code: 'Cipro (CYP)' },
    { code: 'Colombia (COP)' },
    { code: 'Comore (COM)' },
    { code: 'Congo (CDF)' },
    { code: 'Corea del Nord (KPW)' },
    { code: 'Corea del Sud (KRW)' },
    { code: 'Costa d\'Avorio (XOF)' },
    { code: 'Costa Rica (CRC)' },
    { code: 'Croazia (HRK)' },
    { code: 'Cuba (CUP)' },
    { code: 'Danimarca (DKK)' },
    { code: 'Dominica (XCD)' },
    { code: 'Ecuador (USD)' },
    { code: 'Egitto (EGP)' },
    { code: 'El Salvador (SVC)' },
    { code: 'Eritrea (ERN)' },
    { code: 'Estonia (EEK)' },
    { code: 'Eswatini (SZL)' },
    { code: 'Etiopia (ETB)' },
    { code: 'Figi (FJD)' },
    { code: 'Filippine (PHP)' },
    { code: 'Finlandia (EUR)' },
    { code: 'Francia (FRF)' },
    { code: 'Gabon (GAB)' },
    { code: 'Gambia (GMD)' },
    { code: 'Georgia (GEL)' },
    { code: 'Ghana (GHS)' },
    { code: 'Giamaica (JMD)' },
    { code: 'Giappone (JPY)' },
    { code: 'Gibilterra (GIP)' },
    { code: 'Grecia (EUR)' },
    { code: 'Grenada (XCD)' },
    { code: 'Guadalupa (EUR)' },
    { code: 'Guatemala (GTQ)' },
    { code: 'Guinea (GNF)' },
    { code: 'Guinea Equatoriale (GNQ)' },
    { code: 'Guinea-Bissau (GNX)' },
    { code: 'Guyana (GYD)' },
    { code: 'Haiti (HTG)' },
    { code: 'Honduras (HNL)' },
    { code: 'Hong Kong (HKD)' },
    { code: 'India (INR)' },
    { code: 'Indonesia (IDR)' },
    { code: 'Irlanda (EUR)' },
    { code: 'Islanda (ISK)' },
    { code: 'Israele (ILS)' },
    { code: 'Italia (EUR)' },
    { code: 'Jamaica (JMD)' },
    { code: 'Giappone (JPY)' },
    { code: 'Giordania (JOD)' },
    { code: 'Kazakistan (KZT)' },
    { code: 'Kenia (KES)' },
    { code: 'Kirghizistan (KGS)' },
    { code: 'Kiribati (AUD)' },
    { code: 'Kuwait (KWD)' },
    { code: 'Laos (LAK)' },
    { code: 'Lesotho (LSL)' },
    { code: 'Lettonia (LVL)' },
    { code: 'Libano (LBP)' },
    { code: 'Liberia (LRD)' },
    { code: 'Libia (LYD)' },
    { code: 'Liechtenstein (CHF)' },
    { code: 'Lituania (LTL)' },
    { code: 'Lussemburgo (EUR)' },
    { code: 'Macedonia (MKD)' },
    { code: 'Madagascar (MGA)' },
    { code: 'Malawi (MWK)' },
    { code: 'Malesia (MYR)' },
    { code: 'Mali (CFA)' },
    { code: 'Malta (EUR)' },
    { code: 'Marocco (MAD)' },
    { code: 'Mauritius (MUR)' },
    { code: 'Mauritania (MRU)' },
    { code: 'Messico (MXN)' },
    { code: 'Moldavia (MDL)' },
    { code: 'Monaco (EUR)' },
    { code: 'Mongolia (MNT)' },
    { code: 'Mozambico (MZN)' },
    { code: 'Namibia (NAD)' },
    { code: 'Nauru (AUD)' },
    { code: 'Nepal (NPR)' },
    { code: 'Nicaragua (NIO)' },
    { code: 'Niger (NGN)' },
    { code: 'Nigeria (NGN)' },
    { code: 'Niue (AUD)' },
    { code: 'Norvegia (NOK)' },
    { code: 'Nuova Zelanda (NZD)' },
    { code: 'Oman (OMR)' },
    { code: 'Paesi Bassi (EUR)' },
    { code: 'Pakistan (PKR)' },
    { code: 'Palau (USD)' },
    { code: 'Panama (PAB)' },
    { code: 'Papua Nuova Guinea (PGK)' },
    { code: 'Paraguay (PYG)' },
    { code: 'Perù (PEN)' },
    { code: 'Polonia (PLN)' },
    { code: 'Portogallo (EUR)' },
    { code: 'Qatar (QAR)' },
    { code: 'Repubblica Ceca (CZK)' },
    { code: 'Repubblica Dominicana (DOP)' },
    { code: 'Romania (RON)' },
    { code: 'Ruanda (RWF)' },
    { code: 'Saint Kitts e Nevis (XCD)' },
    { code: 'Saint Lucia (SBD)' },
    { code: 'Saint Vincent e Grenadine (SVD)' },
    { code: 'Samoa (WSK)' },
    { code: 'San Marino (EUR)' },
    { code: 'Sao Tome e Principe (STN)' },
    { code: 'Senegal (XOF)' },
    { code: 'Serbia (RSD)' },
    { code: 'Seychelles (SCR)' },
    { code: 'Sierra Leone (SLL)' },
    { code: 'Singapore (SGD)' },
    { code: 'Slovacchia (SKK)' },
    { code: 'Slovenia (EUR)' },
    { code: 'Isole Solomon (SBD)' },
    { code: 'Somalia (SOS)' },
    { code: 'Sri Lanka (LKR)' },
    { code: 'Stati Uniti (USD)' },
    { code: 'Sud Africa (ZAR)' },
    { code: 'Sudan (SDG)' },
    { code: 'Suriname (SRD)' },
    { code: 'Svezia (SEK)' },
    { code: 'Swaziland (SZL)' },
    { code: 'Siria (SYP)' },
    { code: 'Tadzhikistan (TJS)' },
    { code: 'Taiwan (TWD)' },
    { code: 'Tanzania (TZS)' },
    { code: 'Tailandia (THB)' },
    { code: 'Togo (GHS)' },
    { code: 'Tonga (TOP)' },
    { code: 'Trinidad e Tobago (TTD)' },
    { code: 'Tunisia (TND)' },
    { code: 'Turchia (TRY)' },
    { code: 'Tuvalu (AUD)' },
    { code: 'Uganda (UGX)' },
    { code: 'Ucraina (UAH)' },
    { code: 'Uruguay (UYU)' },
    { code: 'Uzbekistan (UZS)' },
    { code: 'Vanuatu (VUV)' },
    { code: 'Vaticano (EUR)' },
    { code: 'Venezuela (VES)' },
    { code: 'Vietnam (VND)' },
    { code: 'Zambia (ZMW)' },
    { code: 'Zimbabwe (ZWD)' }
];


    // Imposta la valuta selezionata se non è già stata passata
    if (!this.selectedCurrency) {
      this.selectedCurrency = this.currencies.find(c => c.code === 'EUR') || this.currencies[0];
    }
  }

  onCurrencyChange(newCurrency: { code: string }) {
    this.selectedCurrency = newCurrency;
    this.selectedCurrencyChange.emit(newCurrency);
  }
}
